### ISSUE TITLE
Bunny connection establishment can fail and should be handled by MM

### ISSUE THREAD

**Issue by bradrobertson** [influitive/multiple_man#5]
See [this exception](https://app.honeybadger.io/projects/39907/faults/12573737#notice-summary). These seem to happen when we have network blips in our system. There's actually quite a few errors that can happen based on network issues.

I'm not sure the best strategy here but we should have some sort of retry mechanism that maybe sleeps for a second or 2 each time. Here are some others we should handle:

https://app.honeybadger.io/projects/39907/faults/12578440#notice-summary

**Comment by bradrobertson** [comment]
https://app.honeybadger.io/projects/39907/faults/12618891#notice-trace

**Comment by ryanbrunner** [comment]
This has been handled in 0.7.0.
